Stack:
  Region: us-east-1
  StackName: testenv
  TemplateURL: 'https://s3.amazonaws.com/nemac-cloudformation/master/templates/drupal-environment.yaml'
  Capabilities:
  - CAPABILITY_NAMED_IAM
  Parameters:
    DatabaseName: ''
    ProjectStack: 'testapp'
    GitBranch: 'exp-eb'
    GitOAuthToken: '<PERSONAL GIT OAUTH TOKEN>'
    GitRepository: 'jwilson8767/cohesivefire.nemac.org'
    InstanceType: 't2.nano'
    MySQLInstanceStack: 'testmysql'
    RetainDatabase: 'no'
    SolutionStackName: '64bit Amazon Linux 2016.09 v2.3.0 running PHP 7.0'

