AWSTemplateFormatVersion: '2010-09-09'
Description: 'A private S3 bucket which can be used by other stacks for codepipeline and Elastic Beanstalk artifact storage.'
Outputs:
  CodePipelineRole:
    Description: 'CodePipeline role ARN for this artifact bucket'
    Export:
      Name: !Sub '${AWS::StackName}-CodePipelineRole'
    Value:
      !GetAtt "CodePipelineRole.Arn"
  DomainName:
    Description: 'Url to the S3 Bucket'
    Export:
      Name: !Sub '${AWS::StackName}-DomainName'
    Value:
      !GetAtt "ArtifactBucket.DomainName"
Resources:
  ArtifactBucket:
    Properties:
      AccessControl: 'Private'
      BucketName: !Sub 'nemac-${AWS::StackName}'
    Type: 'AWS::S3::Bucket'
  CodePipelineRole:
    DependsOn: 'ArtifactBucket'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: 'Allow'
          Principal:
            Service: 'codepipeline.amazonaws.com'
        Version: '2012-10-17'
      Path: '/'
      Policies:
      - PolicyDocument:
          Statement:
          - Action: ['s3:getObject', 's3:putObject', 's3:listBucket']
            Effect: 'Allow'
            Resource: !Sub 'arn:aws:s3:::nemac-${AWS::StackName}/*'
          Version: '2012-10-17'
        PolicyName: !Sub 'cf-codepipeline-policy-${AWS::StackName}-'
      RoleName: !Sub 'cf-${AWS::StackName}-codepipeline-role'
    Type: 'AWS::IAM::Role'
