AWSTemplateFormatVersion: '2010-09-09'
Description: 'A public S3 bucket which can serve assets for other stacks.'
Outputs:
  DomainName:
    Description: 'Url to the S3 Bucket'
    Export:
      Name: !Sub '${AWS::StackName}-DomainName'
    Value:
      !GetAtt "AssetBucket.DomainName"
Resources:
  AssetBucket:
    DeletionPolicy: 'Retain'
    Properties:
      BucketName: !Sub 'nemac-${AWS::StackName}'
    Type: 'AWS::S3::Bucket'
  AssetBucketPolicy:
    DeletionPolicy: 'Retain'
    DependsOn: 'AssetBucket'
    Properties:
      Bucket: !Sub 'nemac-${AWS::StackName}'
      PolicyDocument:
        Statement:
        - Action: ['s3:GetObject']
          Effect: 'Allow'
          Principal: '*'
          Resource: !Sub 'arn:aws:s3:::nemac-${AWS::StackName}/*'
    Type: 'AWS::S3::BucketPolicy'
