---
project: customresources
default-region: us-east-1
code-bucket: nemac-cloudformation-customresources
apps:
  - gordon.contrib.lambdas
lambdas:
  codepipeline:
    code: codepipeline
    handler: code.handler
    runtime: python
    description: Provides creation/deletion of codepipeline actions to support multi-environment codepipelines.
    timeout: 50
  encryptedvalue:
    code: encryptedvalue
    handler: code.handler
    runtime: python
    description: Provides creation/deletion of codepipeline actions to support multi-environment codepipelines.
    timeout: 50
