Stack:
  Region: us-east-1
  StackName: v1-someproject-com
  TemplateURL: 'https://s3.amazonaws.com/nemac-cloudformation/master/templates/drupal-environment.yaml'
  Capabilities:
    - CAPABILITY_NAMED_IAM
  Parameters:
    DatabaseName: ''
    ProjectStack: 'testapp'
    GitBranch: 'prod-v1'
    GitOAuthToken: '<PERSONAL GIT OAUTH TOKEN>'
    GitRepository: 'jwilson8767/cohesivefire.nemac.org'
    InstanceType: 't2.nano'
    MySQLInstanceStack: 'drupal-mysql56'
    RetainDatabase: 'no'
    SolutionStackName: '64bit Amazon Linux 2017.03 v2.7.1 running Multi-container Docker 17.03.1-ce (Generic)'

