AWSTemplateFormatVersion: '2010-09-09'
Description: 'Provisions IAM roles and network resources needed to provision other stacks in this Region.'
Parameters:
  ExistingArtifactBucket:
    Description: 'If an artifact bucket already exists, enter its name here. (Must be in this region)'
    Type: String
  ExistingAssetBucket:
    Description: 'If an asset bucket already exists, enter its name here. (Must be in this region)'
    Type: String
  ExistingSecretsBucket:
    Description: 'If a secrets bucket already exists, enter its name here. (Does not need to be in this region)'
    Type: String
Conditions:
  NotHasExistingArtifactBucket: !Equals [!Ref 'ExistingArtifactBucket', '']
  NotHasExistingAssetBucket: !Equals [!Ref 'ExistingAssetBucket', '']
  NotHasExistingSecretsBucket: !Equals [!Ref 'ExistingSecretsBucket', '']
Resources:
  # The Artifact store bucket is used for artifacts created by CodePipeline and Elastic Beanstalk when pulling down/testing git repos.
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Condition: NotHasExistingArtifactBucket
    DeletionPolicy: 'Delete'
    Properties:
      BucketName: !Sub 'nemac-artifacts-${AWS::Region}'
  # The Asset Bucket is used for static assets that should be publicly accessible.
  AssetBucket:
    Type: AWS::S3::Bucket
    Condition: NotHasExistingAssetBucket
    DeletionPolicy: 'Retain'
    Properties:
      BucketName: !Sub 'nemac-assets-${AWS::Region}'
  AssetBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: AssetBucket
    Condition: NotHasExistingAssetBucket
    DeletionPolicy: 'Retain'
    Properties:
      Bucket: !Sub 'nemac-assets-${AWS::Region}'
      PolicyDocument:
        Statement:
        - Action: ['s3:GetObject']
          Effect: 'Allow'
          Principal: '*'
          Resource: !Sub 'arn:aws:s3:::nemac-assets-${AWS::Region}/*/public/*'
  SecretsBucket:
    Type: AWS::S3::Bucket
    Condition: NotHasExistingSecretsBucket
    DeletionPolicy: 'Retain'
    Properties:
      BucketName: !Sub 'nemac-secrets-${AWS::Region}'
  SecretsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: SecretsBucket
    Condition: NotHasExistingSecretsBucket
    DeletionPolicy: 'Retain'
    Properties:
      Bucket: !Sub 'nemac-secrets-${AWS::Region}'
      PolicyDocument:
        Statement:
          - "Effect":"Deny"
            "Principal":"*"
            "Action":"s3:*"
            "Resource":["arn:aws:s3:::nemac-secrets"
            "arn:aws:s3:::nemac-secrets/*"]
            "Condition":{"StringNotLike":{"aws:userId":["AROAJ6WATZNOFV7HFZ5WA:*"
            "AROAJTCC6ELV5J4SCDZBI:*"
            "AIDAIC5NTOUZ76EAYKHXC"]}}}
          - "Sid":"AllowListDirectory-live-nemac-org"
            "Effect":"Allow"
            "Principal":{"AWS":"arn:aws:iam::479394595410:role/live-nemac-org"}
            "Action":"s3:ListBucket"
            "Resource":["arn:aws:s3:::nemac-secrets"
            "arn:aws:s3:::nemac-secrets/*"]
            "Condition":{"StringLike":{"s3:prefix":"live-nemac-org/*"}}
          - "Sid":"AllowGetPut-live-nemac-org"
            "Effect": "Allow"
            "Principal":{"AWS":"arn:aws:iam::479394595410:role/live-nemac-org"}
            "Action":
              - "s3:GetObject"
              - "s3:GetObjectVersion"
              - "s3:PutObject"
              - "s3:DeleteObject"
            "Resource":"arn:aws:s3:::nemac-secrets/live-nemac-org/*"
          - "Sid":"AllowListDirectory-staging-nemac-org"
            "Effect":"Allow"
            "Principal":{"AWS":"arn:aws:iam::479394595410:role/staging-nemac-org"}
            "Action":"s3:ListBucket"
            "Resource":["arn:aws:s3:::nemac-secrets",
            "arn:aws:s3:::nemac-secrets/*"]
            "Condition": {"StringLike":{"s3:prefix":"staging-nemac-org/*"}}
          - "Sid":"AllowGetPut-staging-nemac-org"
            "Effect":"Allow"
            "Principal": {"AWS":"arn:aws:iam::479394595410:role/staging-nemac-org"}
            "Action":
            - "s3:GetObject"
            - "s3:GetObjectVersion"
            - "s3:PutObject"
            - "s3:DeleteObject"
            "Resource":"arn:aws:s3:::nemac-secrets/staging-nemac-org/*"
  # VPC for all CloudFormation resources in this region.
  VPC:
    Properties:
      CidrBlock: '172.17.0.0/16'
      EnableDnsHostnames: 'true'
      EnableDnsSupport: 'true'
      Tags:
      - Key: 'Name'
        Value: !Ref AWS::StackName
    Type: AWS::EC2::VPC
  # The InternetGateway allows egress from the VPC
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
    Properties: {}
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn: ['InternetGateway', 'VPC']
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
  InternetGatewayRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: VPC
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: 'Application'
        Value: !Ref AWS::StackId
      - Key: Network
        Value: Public
  InternetGatewayRouteTableAssociation:
    Type: AWS::EC2::Route
    DependsOn: ['InternetGatewayAttachment','InternetGatewayRouteTable']
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref InternetGatewayRouteTable
  # One subnet per Availability Zone is sufficient for drupal web servers.
  SubnetA:
    Type: AWS::EC2::Subnet
    DependsOn: VPC
    Properties:
      AvailabilityZone: !Sub '${AWS::Region}a'
      CidrBlock: '172.17.0.0/22'
      MapPublicIpOnLaunch: 'false'
      VpcId: !Ref VPC
  SubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: ['InternetGateway', 'SubnetA']
    Properties:
      RouteTableId: !Ref InternetGatewayRouteTable
      SubnetId: !Ref SubnetA
  SubnetB:
    Type: AWS::EC2::Subnet
    DependsOn: VPC
    Properties:
      AvailabilityZone: !Sub '${AWS::Region}b'
      CidrBlock: '172.17.4.0/22'
      MapPublicIpOnLaunch: 'false'
      VpcId: !Ref VPC
  SubnetBRouteTableAssociation:
    DependsOn: ['InternetGateway', 'SubnetB']
    Properties:
      RouteTableId: !Ref InternetGatewayRouteTable
      SubnetId: !Ref SubnetB
    Type: AWS::EC2::SubnetRouteTableAssociation
  # Defines Security Groups RDS can create endpoints in.
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    DependsOn: ['SubnetA', 'SubnetB']
    Properties:
      DBSubnetGroupDescription: 'default'
      SubnetIds:
        - !Ref SubnetA
        - !Ref SubnetB
      Tags: []
Outputs:
  ArtifactStore:
    Description: 'S3 Bucket name for artifacts'
    Export:
      Name: !Sub '${AWS::StackName}-ArtifactStore'
    Value: !Sub 'elasticbeanstalk-${AWS::Region}-${AWS::AccountId}'
  AssetStore:
    Description: 'S3 Bucket name'
    Export:
      Name: !Sub '${AWS::StackName}-AssetStore'
    Value: !If ['NotHasExistingAssetBucket',!Sub 'nemac-assets-${AWS::Region}',!Ref ExistingAssetBucket]
  AssetStoreUrl:
    Description: 'Url to the Asset Store S3 Bucket'
    Export:
      Name: !Sub '${AWS::StackName}-AssetStoreUrl'
    Value: !If ['NotHasExistingAssetBucket', !GetAtt 'AssetBucket.DomainName', !Sub 'https://s3.amazonaws.com/${ExistingAssetBucket}/']
  VpcId:
    Description: 'VpcId'
    Export:
      Name: !Sub '${AWS::StackName}-VpcId'
    Value: !Ref VPC
  RDSSubnetGroup:
    Description: 'RDS Subnet Group Id'
    Export:
      Name: !Sub '${AWS::StackName}-RDSSubnetGroup'
    Value: !Ref RDSSubnetGroup
  SubnetA:
    Description: 'Subnet ID of Subnet A'
    Export:
      Name: !Sub '${AWS::StackName}-SubnetA'
    Value: !Ref SubnetA
  SubnetB:
    Description: 'Subnet ID of Subnet B'
    Export:
      Name: !Sub '${AWS::StackName}-SubnetB'
    Value: !Ref SubnetB
